export enum Configuration {
	DBPORT = 'PG_PORT',
	HOST = 'PG_HOST',
	USERNAME = 'PG_USER',
	PASSWORD = 'PG_PASS',
	DATABASE = 'PGDB_NAME',
	JWT_SECRET = 'JWT_SECRET',
	JWT_NAME = 'JWT_NAME',
	APP_PORT = 'APP_PORT',
	JWT_EXPIRETIME = 'JWT_EXPIRETIME',
	PG_SYNC = 'PG_SYNC',
	PG_EXT_PORT = 'POSTGRES_PORT_EXTERNAL',
}
