FROM  alpine:latest as builder
ENV ALPINE_MIRROR "http://dl-cdn.alpinelinux.org/alpine"
RUN echo "${ALPINE_MIRROR}/edge/main" >> /etc/apk/repositories
RUN apk add --no-cache nodejs-current curl --repository="http://dl-cdn.alpinelinux.org/alpine/edge/community"
RUN curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
WORKDIR /app
COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN pnpm i --shamefully-hoist --prod
# Multi-stage build
FROM node:alpine
WORKDIR /app
COPY --from=builder /app .
COPY . .
EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]
