export * from './ICategorias';
export * from './ICompetencia';
export * from './IComportamientos';
export * from './IEvaluaciones';
export * from './INiveles';
export * from './IOrganigrama';
export * from './IUser';
export * from './IValoracion';
export * from './Role';
